<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="four_wheel_diff_bot">

  <!-- Include general macros and sensors -->
  <!-- <xacro:include filename="common.xacro" /> -->
  <xacro:include filename="inertial_macros.xacro" />
  <xacro:include filename="lidar.xacro" />
  <xacro:include filename="depth_camera.xacro" />

  <!-- Robot dimensions and properties -->
  <xacro:property name="chassis_length" value="0.35" />
  <xacro:property name="chassis_width" value="0.3" />
  <xacro:property name="chassis_height" value="0.08" />
  <xacro:property name="chassis_mass" value="4.0" />
  <xacro:property name="wheel_radius" value="0.05" />
  <xacro:property name="wheel_width" value="0.02" />
  <xacro:property name="wheel_mass" value="0.5" />

  <!-- Chassis link -->
  <link name="chassis">
    <inertial>
      <mass value="${chassis_mass}" />
      <origin xyz="0 0 0" rpy="0 0 0" />
      <inertia ixx="0.03" iyy="0.03" izz="0.05" ixy="0.0" ixz="0.0" iyz="0.0" />
    </inertial>
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
      </geometry>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0" />
      <material name="black" />
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
      </geometry>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0" />
    </collision>
  </link>

  <!-- Macro to define each wheel and joint -->
  <xacro:macro name="wheel" params="side x y">
    <link name="${side}_wheel">
      <inertial>
        <mass value="${wheel_mass}" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.001" iyy="0.001" izz="0.002" ixy="0.0" ixz="0.0" iyz="0.0" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="1.5707 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
        <material name="gray" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="1.5707 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
      </collision>
    </link>

    <joint name="${side}_wheel_joint" type="continuous">
      <parent link="chassis" />
      <child link="${side}_wheel" />
      <origin xyz="${x} ${y} 0" rpy="0 0 0" />
      <axis xyz="0 1 0" />
    </joint>
  </xacro:macro>

  <!-- Wheels: front_left, front_right, rear_left, rear_right -->
  <xacro:wheel side="front_left" x="0.15" y="0.15" />
  <xacro:wheel side="front_right" x="0.15" y="-0.15" />
  <xacro:wheel side="rear_left" x="-0.15" y="0.15" />
  <xacro:wheel side="rear_right" x="-0.15" y="-0.15" />

  <!-- ros2_control transmission interface -->
  <ros2_control name="diff_drive_controller" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>

    <joint name="front_left_wheel_joint">
      <command_interface name="velocity" />
      <state_interface name="velocity" />
    </joint>
    <joint name="front_right_wheel_joint">
      <command_interface name="velocity" />
      <state_interface name="velocity" />
    </joint>
    <joint name="rear_left_wheel_joint">
      <command_interface name="velocity" />
      <state_interface name="velocity" />
    </joint>
    <joint name="rear_right_wheel_joint">
      <command_interface name="velocity" />
      <state_interface name="velocity" />
    </joint>
  </ros2_control>

</robot>