<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Robot Variables -->
    <xacro:property name="chassis_length" value="0.35" />
    <xacro:property name="chassis_width" value="0.3" />
    <xacro:property name="chassis_height" value="0.08" />
    <xacro:property name="chassis_mass" value="4.0" />
    <xacro:property name="wheel_radius" value="0.05" />
    <xacro:property name="wheel_thickness" value="0.018" />
    <xacro:property name="wheel_mass" value="0.3" />
    <xacro:property name="wheel_offset_x" value="0.13" />
    <xacro:property name="wheel_offset_y" value="${chassis_width/2 + wheel_thickness/2}" />
    <xacro:property name="wheel_offset_z" value="0.0" />

    <gazebo>
        <!-- Four Wheeled Differential Drive Robot -->
        <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
            <!-- Wheels -->
            <left_joint>rear_left_wheel_joint</left_joint>
            <left_joint>front_left_wheel_joint</left_joint>
            <right_joint>rear_right_wheel_joint</right_joint>
            <right_joint>front_right_wheel_joint</right_joint>
            <!-- Wheel params -->
            <wheel_radius>${wheel_radius}</wheel_radius>
            <wheel_separation>${wheel_offset_y*2}</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>
            <wheel_separation>${wheel_offset_y*2}</wheel_separation>
            <!-- Limits -->
            <max_linear_acceleration>2.0</max_linear_acceleration>
            <!-- Frames -->
            <frame_id>odom</frame_id>
            <child_frame_id>base_link</child_frame_id>
            <!-- Output -->
            <tf_topic>/tf</tf_topic>
            <topic>cmd_vel</topic>
            <odom_topic>odom</odom_topic>
            <odom_publisher_frequency>30</odom_publisher_frequency>
        </plugin>

        <!-- Joint State Publisher -->
        <plugin filename="gz-sim-joint-state-publisher-system"
            name="gz::sim::systems::JointStatePublisher">
            <topic>joint_states</topic>
            <joint_name>front_left_wheel_joint</joint_name>
            <joint_name>front_right_wheel_joint</joint_name>
            <joint_name>rear_left_wheel_joint</joint_name>
            <joint_name>rear_right_wheel_joint</joint_name>
        </plugin>
    </gazebo>


</robot>