controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    mecanum_cont:
      type: mecanum_drive_controller/MecanumDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

mecanum_cont:
  ros__parameters:
    publish_rate: 50.0

    base_frame_id: base_link
    odom_frame_id: odom

    # Individual wheel joint names for mecanum drive
    front_left_wheel_joint: "front_left_wheel_joint"
    front_right_wheel_joint: "front_right_wheel_joint"
    rear_left_wheel_joint: "rear_left_wheel_joint"
    rear_right_wheel_joint: "rear_right_wheel_joint"

    # Robot geometry - update according to your actual URDF
    wheel_separation_x: 0.318  # Distance between front and rear axles
    wheel_separation_y: 0.318  # Distance between left and right wheels (was wheel_separation)
    wheel_radius: 0.05

    # Kinematics - set to false for regular wheels, true for mecanum wheels
    # If you have regular wheels but want omnidirectional control, keep as false
    wheels_are_mecanum: false

    use_stamped_vel: false

    # Odometry settings
    enable_odom_tf: true
    open_loop: false
    
    # Command timeout
    cmd_vel_timeout: 0.5
    publish_limited_velocity: true
    velocity_rolling_window_size: 10

    # Pose and twist covariance
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    # Linear velocity limits
    linear:
      x:
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: false
        max_velocity: 1.0
        min_velocity: -1.0
        max_acceleration: 1.0
        min_acceleration: -1.0
        max_jerk: 0.0
        min_jerk: 0.0
      y:
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: false
        max_velocity: 1.0
        min_velocity: -1.0
        max_acceleration: 1.0
        min_acceleration: -1.0
        max_jerk: 0.0
        min_jerk: 0.0

    # Angular velocity limits
    angular:
      z:
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: false
        max_velocity: 1.0
        min_velocity: -1.0
        max_acceleration: 1.0
        min_acceleration: -1.0
        max_jerk: 0.0
        min_jerk: 0.0

joint_broad:
  ros__parameters: {}