controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 50.0
    # pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    # twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]


    base_frame_id: base_link

    # Updated wheel joint names for 4WD
    left_wheel_names: ['front_left_wheel_joint', 'rear_left_wheel_joint']
    right_wheel_names: ['front_right_wheel_joint', 'rear_right_wheel_joint']

    wheels_per_side: 2  # 2 wheels on each side for 4WD

    # Update these values according to your actual URDF geometry
    wheel_separation: 0.318  # auto-calculated from URDF
    wheel_radius: 0.05

    use_stamped_vel: false

    # Optional improvements for control
    cmd_vel_timeout: 0.25  # Timeout for receiving velocity commands
    enable_odom_tf: true  # If you are using robot_localization, set to false, otherwise true

    # Wheel separation and radius multipliers (if you want to adjust these for specific robot performance)
    wheel_separation_multiplier: 1.5  # Default: 1.0
    wheel_radius_multiplier: 1.0      # Default: 1.0

    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 2.0     # Max forward velocity (m/s)
        has_acceleration_limits: true
        max_acceleration: 20.0  # Max acceleration (m/s^2)
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 4.0     # Max angular velocity (rad/s)
        has_acceleration_limits: true
        max_acceleration: 25.0  # Max angular acceleration (rad/s^2)

    # Optional parameters:
    # If you need velocity or acceleration limits for other parameters, uncomment and adjust them here.
    # linear.x.has_jerk_limits: false
    # angular.z.has_jerk_limits: false
    # ... (Additional limits can be set if required)
