controller_manager:
  ros__parameters:
    update_rate: 30

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_link

    left_wheel_names: ['front_left_wheel_joint', 'rear_left_wheel_joint']
    right_wheel_names: ['front_right_wheel_joint', 'rear_right_wheel_joint']
    wheels_per_side: 2

    wheel_separation: 0.297    # distance between left and right wheels
    wheel_radius: 0.05         # update if changed from original 0.033

    use_stamped_vel: false
    open_loop: false

    # Enable TF publishing for odom
    enable_odom_tf: true
    odom_frame_id: odom

    # Odom topic
    odom_topic: odom
    pose_covariance_diagonal: [0.001, 0.001, 99999.0, 99999.0, 99999.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 99999.0, 99999.0, 99999.0, 0.03]

    cmd_vel_timeout: 0.25
    publish_limited_velocity: true
    velocity_rolling_window_size: 10
